[package]
name = "matdemo"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
material-yew = { path = ".." }
wasm-bindgen = "0.2"


[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
